# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\"4\n\nASRRequest\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\x12\x11\n\thot_words\x18\x02 \x01(\t\"!\n\x0b\x41SRResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t23\n\x03\x41SR\x12,\n\tStreamASR\x12\x0b.ASRRequest\x1a\x0c.ASRResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ASRREQUEST']._serialized_start=13
  _globals['_ASRREQUEST']._serialized_end=65
  _globals['_ASRRESPONSE']._serialized_start=67
  _globals['_ASRRESPONSE']._serialized_end=100
  _globals['_ASR']._serialized_start=102
  _globals['_ASR']._serialized_end=153
# @@protoc_insertion_point(module_scope)
